[package]
name = "Capter"
version = "1.1.0"
description = "A simple cross-platform screenshot tool"
edition = "2021"
authors = ["decipher3114 <decipher3114@gmail.com>"]
build = "build.rs"

[dependencies]
active-win-pos-rs = "0.8.3"
arboard = { version = "3.4.0", features = ["wayland-data-control", "wl-clipboard-rs"] }
chrono = "0.4.38"
display-info = { version = "0.5.1"}
iced = { git = "https://github.com/iced-rs/iced", branch = "master", features = ["advanced", "canvas", "multi-window", "image", "tokio", "svg"] }
rdev = { git = "https://github.com/rustdesk-org/rdev", branch = "master"}
rfd = { version = "0.14", features = ["gtk3", "tokio"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.39.2", features = ["full", "rt"] }
toml = "0.8.19"
tray-icon = "0.17.0"
xcap = "0.0.13"

[target.'cfg( target_os = "windows" )'.build-dependencies]
winresource = "0.1"

[package.metadata.winresource]
ProductName = "Capter"

[package.metadata.packager]
product-name = "Capter"
version = "1.0.1"
identifier = "app.decipher.capter"
authors = ["decipher3114 <decipher3114@gmail.com>"]
publisher = "decipher3114"
category = "Utility"
copyright = "Copyright © 2024"
formats = ["wix", "deb", "pacman", "dmg"]
before-packaging-command = "cargo build --release"
icons = ["assets/icons/windows/icon.ico", "assets/icons/macos/icon.icns", "assets/icons/linux/*"]
out-dir = "target/packages"

[package.metadata.packager.wix]
banner-path = "assets/images/wix_banner.png"
dialog-image-path = "assets/images/dialog_image.png"

[package.metadata.packager.windows]
digest-algorithim = "SHA256"
certificate-thumbprint = "07a9c417660868a4420fe9e2f8b6ac2e1a33228a"
tsp = true
timestamp-url = "http://timestamp.digicert.com"

[package.metadata.packager.deb]
depends = ["libgtk-3-dev", "libxdo-dev", "libayatana-appindicator3-dev", "libxcb1", "libxrandr2", "libdbus-1-3"]

[package.metadata.packager.pacman]
source = ["${pkgname}-${pkgver}.tar.gz::https://github.com/Capter/releases/latest/download/Capter_${pkgver}_x86_64.tar.gz"]
depends = ["gtk3", "xdotool", "libayatana-appindicator", "libxcb", "libxrandr", "dbus"]
