[package]
name = "Capter"
version = "1.0.0"
description = "A simple cross-platform screenshot tool"
edition = "2021"
authors = ["decipher3114 <decipher3114@gmail.com>"]

[dependencies]
active-win-pos-rs = "0.8.3"
arboard = { version = "3.4.0", features = ["wayland-data-control", "wl-clipboard-rs"] }
chrono = "0.4.38"
display-info = { version = "0.5.1"}
iced = { git = "https://github.com/iced-rs/iced", branch = "master", features = ["advanced", "canvas", "multi-window", "image", "tokio", "svg"] }
rdev = { git = "https://github.com/rustdesk-org/rdev", branch = "master"}
rfd = { version = "0.14", features = ["gtk3", "tokio"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.39.2", features = ["full", "rt"] }
toml = "0.8.19"
xcap = "0.0.13"
